-- Sprint 17.1: convert activity_log to a RANGE-partitioned table by created_at.
--
-- Why partition: blueprint v2.0 says activity_log is partitioned monthly
-- from day one. Targeted month queries stay fast as the table grows;
-- archival via DROP PARTITION is O(1) instead of O(n) DELETE; per-month
-- indexes stay cache-resident.
--
-- Plan (single migration, brief table lock — fine for dev, runbook for prod):
--   1. RENAME the existing table to activity_log_legacy. Same with indexes.
--   2. CREATE the new partitioned table with the same column shape. Postgres
--      requires the PRIMARY KEY to INCLUDE the partition key, so the PK is
--      (id, created_at) instead of just (id). The id alone stays UNIQUE via
--      a separate constraint propagated to each partition.
--   3. Create six initial partitions: current month, 3 months back, 3 forward.
--      That covers historical inserts during backfill plus near-future writes
--      before the daily auto-create cron (later sprint task) takes over.
--   4. INSERT INTO ... SELECT FROM legacy. Existing rows are routed into the
--      right monthly partition by their created_at value.
--   5. DROP legacy.
--   6. Recreate indexes + RLS policy + grants on the new parent — Postgres
--      automatically propagates declared indexes to all current and future
--      partitions, so we only define them once on the parent.
--
-- Foreign keys: the original activity_log had no FKs (intentional, to avoid
-- cascade fan-out from user deletes). Keep that.

-- --- 1. Rename existing table + indexes so we can rebuild on the same names. ---
ALTER TABLE "activity_log" RENAME TO "activity_log_legacy";
ALTER INDEX "idx_activity_log_company_created_at" RENAME TO "idx_activity_log_company_created_at_legacy";
ALTER INDEX "idx_activity_log_target"             RENAME TO "idx_activity_log_target_legacy";
ALTER INDEX "idx_activity_log_actor"              RENAME TO "idx_activity_log_actor_legacy";
ALTER INDEX "activity_log_pkey"                   RENAME TO "activity_log_legacy_pkey";

-- --- 2. New partitioned parent. ---
CREATE TABLE "activity_log" (
  "id"             UUID           NOT NULL DEFAULT gen_random_uuid(),
  "company_id"     UUID           NOT NULL,
  "actor_user_id"  UUID,
  "action_type"    TEXT           NOT NULL,
  "target_type"    TEXT,
  "target_id"      UUID,
  "field_changed"  TEXT,
  "metadata"       JSONB,
  "created_at"     TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
  -- Partition-key inclusion in PK is a Postgres requirement. The composite
  -- PK is unique because `id` is generated by gen_random_uuid()  — practically
  -- never collides — so the only role created_at plays in identity is satisfying
  -- this rule.
  CONSTRAINT "activity_log_pkey" PRIMARY KEY ("id", "created_at")
) PARTITION BY RANGE ("created_at");

-- Tenant-scoped RLS. Same shape as before; policies on the parent propagate
-- to partitions automatically.
ALTER TABLE "activity_log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "activity_log" FORCE ROW LEVEL SECURITY;
CREATE POLICY "activity_log_tenant_isolation" ON "activity_log"
  USING      (company_id = current_setting('app.current_company_id', true)::uuid)
  WITH CHECK (company_id = current_setting('app.current_company_id', true)::uuid);

-- Indexes declared on the parent — Postgres creates a matching index on every
-- partition (existing and future). This is the post-PG11 declarative behavior.
CREATE INDEX "idx_activity_log_company_created_at"
  ON "activity_log" ("company_id", "created_at" DESC);
CREATE INDEX "idx_activity_log_target"
  ON "activity_log" ("target_type", "target_id", "created_at" DESC);
CREATE INDEX "idx_activity_log_actor"
  ON "activity_log" ("actor_user_id", "created_at" DESC);

GRANT SELECT, INSERT, UPDATE, DELETE ON "activity_log" TO app_user;

-- --- 3. Initial six partitions: 3 months back, current, 3 forward. ---
-- Naming convention: activity_log_YYYY_MM. Bounds are [inclusive, exclusive).
-- The daily auto-create cron (later 17.x task) will extend this forward.
CREATE TABLE "activity_log_2026_02" PARTITION OF "activity_log"
  FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');
CREATE TABLE "activity_log_2026_03" PARTITION OF "activity_log"
  FOR VALUES FROM ('2026-03-01') TO ('2026-04-01');
CREATE TABLE "activity_log_2026_04" PARTITION OF "activity_log"
  FOR VALUES FROM ('2026-04-01') TO ('2026-05-01');
CREATE TABLE "activity_log_2026_05" PARTITION OF "activity_log"
  FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');
CREATE TABLE "activity_log_2026_06" PARTITION OF "activity_log"
  FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE "activity_log_2026_07" PARTITION OF "activity_log"
  FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE "activity_log_2026_08" PARTITION OF "activity_log"
  FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');

-- --- 4. Backfill: copy every legacy row into the right partition. ---
-- Postgres routes by created_at automatically; this is a single statement.
-- We bypass RLS by virtue of running as the migration role (neondb_owner).
INSERT INTO "activity_log"
  ("id", "company_id", "actor_user_id", "action_type", "target_type",
   "target_id", "field_changed", "metadata", "created_at")
SELECT
   "id",  "company_id",  "actor_user_id",  "action_type",  "target_type",
   "target_id",  "field_changed",  "metadata",  "created_at"
FROM "activity_log_legacy";

-- Sanity assertion: count of rows in the new parent must match the legacy
-- count. If a stray legacy row sat outside the 7 partition windows the INSERT
-- would have failed with "no partition of relation found for row" — this is
-- belt + suspenders, surfacing the silent miss in DO blocks.
DO $$
DECLARE
  legacy_count  bigint;
  new_count     bigint;
BEGIN
  SELECT count(*) INTO legacy_count FROM "activity_log_legacy";
  SELECT count(*) INTO new_count    FROM "activity_log";
  IF legacy_count <> new_count THEN
    RAISE EXCEPTION 'activity_log partition migration row count mismatch: legacy=%, new=%',
      legacy_count, new_count;
  END IF;
END $$;

-- --- 5. Drop legacy table. ---
-- Indexes go with it. Policy goes with the table. No FK references on it.
DROP TABLE "activity_log_legacy";
